name: Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install npm deps
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: |
          pnpm test:unit
